### ISSUE TITLE
Managed hosting?

### ISSUE THREAD

**Issue by ffMathy** [screeps/screeps#101]
Would it be an idea to offer a managed Screeps hosting service, perhaps backed by AWS under the hood, with a UI?

If the Screeps team did that, they could offer it to automatically be listed as a "certified" server, with a special icon (or in a special list), to show everyone that it has the performance needed for the capacity that it can hold?

It would be a fantastic way for the Screeps team to earn more!

Many workplaces already use Screeps for hiring processes and for their employees. They would be willing to pay for this - they don't want to host themselves.

**Comment by shibdib** [comment]
Please share workplaces using screeps to hire (I'm job hunting haha)

**Comment by ffMathy** [comment]
It's only here in Denmark that I know of companies doing it - sorry!

**Comment by o4kapuk** [comment]
Currently, we don't have plans on providing any services other than the official public mmo game server.
