### ISSUE TITLE
Respawning does not unclaim controller

### ISSUE THREAD

**Issue by ffMathy** [screeps/screeps#102]
I recently clicked the Respawn button in a room on my private server running the latest version.

When I did so, the room controller I had was not unclaimed.

Now I can't respawn in the room without dying instantly. I should have unclaimed it first obviously, but isn't this a bug? What is the rationale behind this?

**Comment by ffMathy** [comment]
It says the controller is now owned by "Screeps" by the way. Will it turn neutral over time?

**Comment by o4kapuk** [comment]
Any idea of how to reproduce this?

**Comment by ffMathy** [comment]
Nope, but if the "Owner" of the controller was set to the string "Screeps", wouldn't we be able to find it that way?

**Comment by o4kapuk** [comment]
No we won't (or at least I won't).
[The respawn method](https://github.com/screeps/backend-local/blob/master/lib/utils.js#L115) looks fine about handling controllers, it works fine at my local server, and we can't fix things without seeing them broken.

**Comment by o4kapuk** [comment]
Unable to reproduce
