### ISSUE TITLE
Unclaim and loosing controller does not remove room from users room list

### ISSUE THREAD

**Issue by bridgescodecamp** [screeps/screeps#103]
The room is not being removed and can still be seen by checking the user using the screeps cli. This is on a private server with the latest code.

**Comment by fireduck64** [comment]
For whatever it is worth, I think I am experiencing this as well.

**Comment by o4kapuk** [comment]
Any idea how it can be reproduced?

**Comment by fireduck64** [comment]
It seemed to be:

- Run private server
- Claim a few rooms
- Fail to upgrade them and lose them

Then observe that storage db shows rooms that you no longer have.
Work around is to note the rooms you actually have and run something like this:
storage.db['users'].update({ username: 'Fireduck' },{ $set: { rooms:  [ 'W2N5', 'W2N6', 'W1N4', 'W1N6' ] }})

**Comment by o4kapuk** [comment]
Thanks for report, we'll take a look.

**Comment by o4kapuk** [comment]
Fixed in [this commit](https://github.com/screeps/storage/commit/293021d047cec1cc367f7b9c47de1843036349f2).
