### ISSUE TITLE
Installation fails on Debian Jessie

### ISSUE THREAD

**Issue by pixartist** [screeps/screeps#107]
Tried installing from nom or directly in the cloned repo, neither worked: 

> gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build', '--jobs', 4 ]
make: Entering directory '/root/screeps/node_modules/isolated-vm/build'
  g++ '-DNODE_GYP_MODULE_NAME=nortti' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' -I/root/.node-gyp/8.11.1/include/node -I/root/.node-gyp/8.11.1/src -I/root/.node-gyp/8.11.1/deps/uv/include -I/root/.node-gyp/8.11.1/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -O3 -fno-omit-frame-pointer -fno-rtti -std=gnu++0x -std=c++14 -g -Wno-unknown-pragmas -MMD -MF ./Release/.deps/Release/obj.target/nortti/src/external_copy_nortti.o.d.raw   -c -o Release/obj.target/nortti/src/external_copy_nortti.o ../src/external_copy_nortti.cc
In file included from ../src/isolate/remote_handle.h:3:0,
                 from ../src/isolate/util.h:6,
                 from ../src/external_copy.h:10,
                 from ../src/external_copy_nortti.cc:1:
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
  rm -f Release/obj.target/nortti.a && ar crs Release/obj.target/nortti.a Release/obj.target/nortti/src/external_copy_nortti.o
  rm -rf "Release/nortti.a" && cp -af "Release/obj.target/nortti.a" "Release/nortti.a"
  g++ '-DNODE_GYP_MODULE_NAME=isolated_vm' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/8.11.1/include/node -I/root/.node-gyp/8.11.1/src -I/root/.node-gyp/8.11.1/deps/uv/include -I/root/.node-gyp/8.11.1/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++14 -g -Wno-unknown-pragmas -MMD -MF ./Release/.deps/Release/obj.target/isolated_vm/src/isolate/allocator.o.d.raw   -c -o Release/obj.target/isolated_vm/src/isolate/allocator.o ../src/isolate/allocator.cc
  g++ '-DNODE_GYP_MODULE_NAME=isolated_vm' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/8.11.1/include/node -I/root/.node-gyp/8.11.1/src -I/root/.node-gyp/8.11.1/deps/uv/include -I/root/.node-gyp/8.11.1/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++14 -g -Wno-unknown-pragmas -MMD -MF ./Release/.deps/Release/obj.target/isolated_vm/src/isolate/class_handle.o.d.raw   -c -o Release/obj.target/isolated_vm/src/isolate/class_handle.o ../src/isolate/class_handle.cc
  g++ '-DNODE_GYP_MODULE_NAME=isolated_vm' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/8.11.1/include/node -I/root/.node-gyp/8.11.1/src -I/root/.node-gyp/8.11.1/deps/uv/include -I/root/.node-gyp/8.11.1/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++14 -g -Wno-unknown-pragmas -MMD -MF ./Release/.deps/Release/obj.target/isolated_vm/src/isolate/environment.o.d.raw   -c -o Release/obj.target/isolated_vm/src/isolate/environment.o ../src/isolate/environment.cc
  g++ '-DNODE_GYP_MODULE_NAME=isolated_vm' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/8.11.1/include/node -I/root/.node-gyp/8.11.1/src -I/root/.node-gyp/8.11.1/deps/uv/include -I/root/.node-gyp/8.11.1/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -Wno-deprecated-declarations -O3 -fno-omit-frame-pointer -std=gnu++0x -std=c++14 -g -Wno-unknown-pragmas -MMD -MF ./Release/.deps/Release/obj.target/isolated_vm/src/isolate/holder.o.d.raw   -c -o Release/obj.target/isolated_vm/src/isolate/holder.o ../src/isolate/holder.cc
In file included from ../src/isolate/holder.cc:2:0:
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
In file included from ../src/isolate/remote_handle.h:3:0,
                 from ../src/isolate/util.h:6,
                 from ../src/isolate/convert_param.h:3,
                 from ../src/isolate/class_handle.h:4,
                 from ../src/isolate/class_handle.cc:1:
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
../src/isolate/holder.cc: In member function 'void ivm::IsolateHolder::Dispose()':
../src/isolate/holder.cc:14:102: error: no matching function for call to 'atomic_exchange(std::shared_ptr<ivm::IsolateEnvironment>*, std::shared_ptr<ivm::IsolateEnvironment>)'
  shared_ptr<IsolateEnvironment> tmp = std::atomic_exchange(&isolate, shared_ptr<IsolateEnvironment>());
                                                                                                      ^
../src/isolate/holder.cc:14:102: note: candidates are:
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:914:5: note: template<class _ITp> _ITp std::atomic_exchange(std::atomic<_ITp>*, _ITp)
     atomic_exchange(atomic<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.9/atomic:914:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:14:102: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> tmp = std::atomic_exchange(&isolate, shared_ptr<IsolateEnvironment>());
                                                                                                      ^
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:919:5: note: template<class _ITp> _ITp std::atomic_exchange(volatile std::atomic<_ITp>*, _ITp)
     atomic_exchange(volatile atomic<_ITp>* __a, _ITp __i) noexcept
     ^
/usr/include/c++/4.9/atomic:919:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:14:102: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'volatile std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> tmp = std::atomic_exchange(&isolate, shared_ptr<IsolateEnvironment>());
                                                                                                      ^
../src/isolate/holder.cc: In member function 'std::shared_ptr<ivm::IsolateEnvironment> ivm::IsolateHolder::GetIsolate()':
../src/isolate/holder.cc:24:34: error: no matching function for call to 'atomic_load(std::shared_ptr<ivm::IsolateEnvironment>*)'
  return std::atomic_load(&isolate);
                                  ^
../src/isolate/holder.cc:24:34: note: candidates are:
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:904:5: note: template<class _ITp> _ITp std::atomic_load(const std::atomic<_ITp>*)
     atomic_load(const atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:904:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:24:34: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const std::atomic<_ITp>'
  return std::atomic_load(&isolate);
                                  ^
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:909:5: note: template<class _ITp> _ITp std::atomic_load(const volatile std::atomic<_ITp>*)
     atomic_load(const volatile atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:909:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:24:34: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const volatile std::atomic<_ITp>'
  return std::atomic_load(&isolate);
                                  ^
In file included from ../src/isolate/environment.cc:1:0:
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
../src/isolate/holder.cc: In member function 'void ivm::IsolateHolder::ScheduleTask(std::unique_ptr<ivm::Runnable>, bool, bool, bool)':
../src/isolate/holder.cc:28:64: error: no matching function for call to 'atomic_load(std::shared_ptr<ivm::IsolateEnvironment>*)'
  shared_ptr<IsolateEnvironment> ref = std::atomic_load(&isolate);
                                                                ^
../src/isolate/holder.cc:28:64: note: candidates are:
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:904:5: note: template<class _ITp> _ITp std::atomic_load(const std::atomic<_ITp>*)
     atomic_load(const atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:904:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:28:64: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> ref = std::atomic_load(&isolate);
                                                                ^
In file included from ../src/isolate/environment.h:8:0,
                 from ../src/isolate/holder.cc:2:
/usr/include/c++/4.9/atomic:909:5: note: template<class _ITp> _ITp std::atomic_load(const volatile std::atomic<_ITp>*)
     atomic_load(const volatile atomic<_ITp>* __a) noexcept
     ^
/usr/include/c++/4.9/atomic:909:5: note:   template argument deduction/substitution failed:
../src/isolate/holder.cc:28:64: note:   'std::shared_ptr<ivm::IsolateEnvironment>' is not derived from 'const volatile std::atomic<_ITp>'
  shared_ptr<IsolateEnvironment> ref = std::atomic_load(&isolate);
                                                                ^
In file included from ../src/isolate/allocator.cc:2:0:
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::data' [-Wmissing-field-initializers]
   v8::StartupData startup_data {};
                                 ^
../src/isolate/environment.h:326:33: warning: missing initializer for member 'v8::StartupData::raw_size' [-Wmissing-field-initializers]
../src/isolate/holder.cc: In member function 'std::shared_ptr<ivm::IsolateEnvironment> ivm::IsolateHolder::GetIsolate()':
../src/isolate/holder.cc:25:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
isolated_vm.target.mk:119: recipe for target 'Release/obj.target/isolated_vm/src/isolate/holder.o' failed
make: *** [Release/obj.target/isolated_vm/src/isolate/holder.o] Error 1
make: *** Waiting for unfinished jobs....
../src/isolate/environment.cc:662:13: warning: 'void ivm::DeserializeInternalFieldsCallback(v8::Local<v8::Object>, int, v8::StartupData, void*)' defined but not used [-Wunused-function]
 static void DeserializeInternalFieldsCallback(Local<Object> /*holder*/, int /*index*/, StartupData /*payload*/, void* /*data*/) {
             ^
make: Leaving directory '/root/screeps/node_modules/isolated-vm/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-0.bpo.9-amd64
gyp ERR! command "/root/.nvm/versions/node/v8.11.1/bin/node" "/root/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /root/screeps/node_modules/isolated-vm
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm verb lifecycle isolated-vm@1.7.11~install: unsafe-perm in lifecycle false
npm verb lifecycle isolated-vm@1.7.11~install: PATH: /root/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/screeps/node_modules/isolated-vm/node_modules/.bin:/root/screeps/node_modules/.bin:/root/.nvm/versions/node/v8.11.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle isolated-vm@1.7.11~install: CWD: /root/screeps/node_modules/isolated-vm
npm info lifecycle isolated-vm@1.7.11~install: Failed to exec install script
npm verb unlock done using /root/.npm/_locks/staging-3917d806cdc9981b.lock for /root/screeps/node_modules/.staging
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: isolated-vm@1.7.11 install: `node-gyp rebuild --release -j 4`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:925:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid isolated-vm@1.7.11
npm verb cwd /root/screeps
npm verb Linux 4.9.0-0.bpo.9-amd64
npm verb argv "/root/.nvm/versions/node/v8.11.1/bin/node" "/root/.nvm/versions/node/v8.11.1/bin/npm" "install" "--verbose"
npm verb node v8.11.1
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@1.7.11 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isolated-vm@1.7.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-07T13_58_11_004Z-debug.log

**Comment by ags131** [comment]
Try using Node 10, there are currently issues compiling IVM for node 8

**Comment by pixartist** [comment]
> Try using Node 10, there are currently issues compiling IVM for node 8

Same issue, isolated_vm will not install

**Comment by ags131** [comment]
It looks like Jessie still uses GCC 4.9, the current version of IVM that screeps uses only compiles on GCC 5. (This was fixed in a later IVM version)

**Comment by pixartist** [comment]
Yep, I upgraded to Debian 10 and now it installs, it just doesn't start
