### ISSUE TITLE
Newly Destroyed Structures Method

### ISSUE THREAD

**Issue by bjr29** [screeps/screeps#113]
Could we have a method that is fired when a structure is destroyed such as: 
`Game.rooms.RoomName.getDestroyStructures()`
Have it return an array of newly destroyed structures in the last tick with structure's stats such as the structure's type, pos, etc. My idea behind this was to have code that replaces an old structure that wasn't removed by the player.

**Comment by o4kapuk** [comment]
Structures now leave ruins with information about the structure.
