### ISSUE TITLE
Recommended way to stop the server?

### ISSUE THREAD

**Issue by ty2u** [screeps/screeps#13]
Hi there,

Impressive work you have here, thanks for sharing!

I've been waiting to buy screeps until you released this server to play around with. Thank you!

I managed to get the server running eventually on Ubuntu 16.04 after some issues. I think mainly I just didn't know the correct versions of everything to use or maybe it wasn't setup quite right on the machine to begin with since it already had a node install on it. But I got it so woohoo! Eventually I will have to create an init script of some sort to start it on boot and whatnot.

I have very little experience with nodejs yet and I have no idea what the correct way to stop the server is. The only way I see is killing the processes which I'm not sure is the best route. Is there a recommended way to stop the server?

Thank you!

**Comment by iKlem** [comment]
Hi.  
I made a manager for that, you can get it [here](https://github.com/iKlem/linux-screeps-server-manager).  
It will always be updated and I want to add more features to it.

**Comment by artch** [comment]
Killing the processes is perfectly safe, the database is flushed to `db.json` file every 3 seconds (you can mod it with `config.storage.dbOptions.autosaveInterval`), there is no real-time I/O, so the state will be consistent anyway.

**Comment by ty2u** [comment]
Awesome, thanks!
