### ISSUE TITLE
Problem with opening the client on steam

### ISSUE THREAD

**Issue by ZYL9** [screeps/screeps#132]
when i'm using steam to open the client. the client keeps in the title-page forever.
if you need any log or screenshot, please let me know. 
It's a really nice game and i'm really want to play it.
thanks!
![捕获](https://user-images.githubusercontent.com/30659977/114541355-347d1f80-9c89-11eb-93e2-46bd9ec95344.PNG)

**Comment by o4kapuk** [comment]
Please drop a ticket into the official Screeps support (contact@screeps.com)
