### ISSUE TITLE
[FEATURE REQUEST] Please add more languages (coding)

### ISSUE THREAD

**Issue by Inf-inity** [screeps/screeps#147]
I think the idea of the game is great, but I would like to see more languages in which you can play the game. By languages I mean programming languages. Above all, I would be happy about a Python support. Several languages would eventually increase the reach of the game if more people who can't do JS could participate.

**Comment by mnowicky** [comment]
there are ways to play the game in python, though I would recommend you just learn javascript. If you can already code well in python switching to js is very quick and easy to do. There are many similarities and most differences are simply syntactic. I, like you, used to code exclusively in python... and actually this game broadened my horizons... I now prefer node and the many js frameworks to python when working on real-world projects. Give it a try!
