### ISSUE TITLE
EventEmitters for mod events

### ISSUE THREAD

**Issue by ags131** [screeps/screeps#16]
I've been messing with modding since the beta, and have a request. Currently, when hooking events, in order to keep from potentially breaking previously loaded mods, we need to store the original function and call it inside our replacement. I'm proposing that EventEmitters be added so that each mod can hook the events without worrying as much about other mods. 

I have a gist with two mods, one that adds the EventEmitters via Proxy, and another demonstrating it in action. 
https://gist.github.com/ags131/1690177425e43bae4a85857d28084a0b

This event pattern also makes it easier to hook common events such as preExpressConfig which is used by mods needing more/earlier control over the routes just by doing `config.backend.on('preExpressConfig',(event,app)=>{ ... })`

I have had pointed out to me in slack that usually events are asynchronous, in node, they are not. From the nodejs [event module documentation](https://nodejs.org/api/events.html):

> When the EventEmitter object emits an event, all of the functions attached to that specific event are called synchronously.

**Comment by artch** [comment]
Yes, we had the same thoughts while making [this commit](https://github.com/screeps/launcher/commit/bbb8d3ec68fa3f006a53505af5e2e8b47dea862d). I'm going to push this in a couple of days. You can send a PR if you wish.

**Comment by ags131** [comment]
Gist updated to reflect onCreateSandbox in 1.0.7

**Comment by artch** [comment]
Implemented in 2.0.0.
