### ISSUE TITLE
standalone console is always out of sync

### ISSUE THREAD

**Issue by mozesmagyar** [screeps/screeps#18]
title says it all: every time I launch the steam client, connect to the private server, and launch the console/code editor it says it's out of sync and to relaunch it.

**Comment by mozesmagyar** [comment]
this was meant to be a double bug for allowing the api to work but when I thought of separating it I didn't turn this one into a bug and left it as a feature

**Comment by ty2u** [comment]
This happens to me if I click the "New window" icon to separate the editor from the window. It pops up but on the top right I get this error: This pop-up editor is out of sync. Please re-open the editor.

**Comment by timeshifter** [comment]
Having the same issue here, local server.

**Comment by xxApvxx** [comment]
Any news available for this issue? Same issue here, and have no ideas to even try.

**Comment by artch** [comment]
This must be fixed now, please update your client.
