### ISSUE TITLE
Missing file, cant download the server

### ISSUE THREAD

**Issue by Dragonisser** [screeps/screeps#19]
It keep saying that it is missing some files.

npm http GET https://registry.npmjs.org/screeps
npm http 200 https://registry.npmjs.org/screeps
npm http GET https://registry.npmjs.org/screeps/-/screeps-1.0.7.tgz
npm http 200 https://registry.npmjs.org/screeps/-/screeps-1.0.7.tgz
npm http GET https://registry.npmjs.org/screeps/common
npm http GET https://registry.npmjs.org/screeps/driver
npm http GET https://registry.npmjs.org/screeps/backend
npm http GET https://registry.npmjs.org/screeps/engine
npm http GET https://registry.npmjs.org/screeps/storage
npm http GET https://registry.npmjs.org/screeps/pathfinding
npm http GET https://registry.npmjs.org/screeps/launcher
npm http 404 https://registry.npmjs.org/screeps/driver
npm http 404 https://registry.npmjs.org/screeps/common
npm http 404 https://registry.npmjs.org/screeps/pathfinding
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'screeps/driver' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'screeps'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by artch** [comment]
What is your Node.js version? Only Node.js 6 or higher is supported, your version seems to be an older one.
