### ISSUE TITLE
Virtual Environment

### ISSUE THREAD

**Issue by ctrlaltdylan** [screeps/screeps#2]
Any reason to create a virtual environment for this application? Docker or Vagrant powered? I would like to deploy it to AWS Lambda but their version of Node is ~4 which isn't compatible according to the docs.

**Comment by sanados** [comment]
imho aws lambda is the wrong place as it is event based not for services.

in screeps slack #servers there are already talks about docker container.

**Comment by ctrlaltdylan** [comment]
I would prefer a docker container as well, it's much more configurable and you're probably right about the lambda idea. At least it can be scaled with a traditional server. I will join the slack channel but keep this issue open until we have a nice virtual environment.

**Comment by artch** [comment]
We don't plan to provide any official images for virtual environment deployments, but you can always come up with your own, the launcher system is very simple.
