### ISSUE TITLE
CPU Limit won't increase

### ISSUE THREAD

**Issue by SchmidtBytes** [screeps/screeps#20]
I reached GCL 2 on my private server. In my overview it says I have a CPU Limit of 40 however my actual limit stays at 30.

**Comment by artch** [comment]
There is no automatic CPU increasing on private servers currently. You can set any desired CPU limit for any user using this CLI command:

```
storage.db['users'].update({username: yourUserName}, {$set: {cpu: 200}});
```

**Comment by Parakoopa** [comment]
But isn't this still a bug, if the overview displays 40?

**Comment by artch** [comment]
Yes, it's an inconsistency between official and private server UI, we'll fix it soon.
