### ISSUE TITLE
IRC or Discord chat?

### ISSUE THREAD

**Issue by digitalfiz** [screeps/screeps#22]
Is there any place that people can gather to discuss contributing or setting this bad boy up?

I want to replace the storage engine with mongodb or even a few others but I have lots of questions.

Also I have questions about running it in cluster form via docker...

**Comment by digitalfiz** [comment]
Found this so ignore me:

http://chat.screeps.com/

**Comment by artch** [comment]
Also, see our forums: http://support.screeps.com/hc/en-us/community/topics/200695985-Private-servers
