### ISSUE TITLE
Messages not working?

### ISSUE THREAD

**Issue by gallexme** [screeps/screeps#28]
Hello
when i get a message and answer it
i still see the notification and
when i try to see the message again i only see mine

http://puu.sh/soL4X/77edc29caf.png

is this happening to you guys aswell?

**Comment by ArronHoltzhausen** [comment]
happening for me as well @gallexme

**Comment by lukaspj** [comment]
Happened for me as well, finding the sender's profile and accessing the chat through there worked for me.

**Comment by o4kapuk** [comment]
Should be fixed now
