### ISSUE TITLE
Random Map Generating?

### ISSUE THREAD

**Issue by gallexme** [screeps/screeps#29]
Will we be able to generate random maps?

**Comment by artch** [comment]
You can use CLI command `map.generateRoom`. 

Please use our [Slack chat](http://chat.screeps.com) to get help. GitHub Issues is for bug reports.

**Comment by gallexme** [comment]
@artch its not for help its a feature request

and
sorry I meant generating random Worlds not map/rooms
as generateRoom only creates one room?
i was expecting that the worlds are always randomly generated on each db/assets/.screepssrc deletion

is this currently possible or is it not, if not are there any plans to implement it?

if not do you accept pull requests?
