### ISSUE TITLE
Couldn't install through NPM

### ISSUE THREAD

**Issue by stephenkall** [screeps/screeps#3]
While trying to install through NPM, I keep getting the following errors:

`npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'screeps/common' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'screeps'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 2.6.32-042stab113.21
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "screeps"
npm ERR! cwd /
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0`

Also, the registry not found cycles if I just re-run the command (through screeps/backend, screeps/driver, etc).

**Comment by artch** [comment]
Only Node.js 4 or higher is supported, your version is 0.10.29.
