### ISSUE TITLE
Badges not working?

### ISSUE THREAD

**Issue by gallexme** [screeps/screeps#30]
Can you guys select Badges?

**Comment by ags131** [comment]
Works fine for me.

**Comment by artch** [comment]
@gallexme GitHub Issues is not a forum, it's a bug tracker. Please only post here when you got a proper bug report, and use our [Slack chat](http://chat.screeps.com) or [forum](http://support.screeps.com/hc/en-us/community/topics/200695985-Private-servers) otherwise.

**Comment by gallexme** [comment]
well okay then a proper bug report 

Screeps Version if known (or site URL)

newest currently

Please describe the expected behaviour
I Should be able to select Badges here:
http://puu.sh/spNFQ/5ab1d5a9d6.png
or here:
http://puu.sh/spNHf/b9276e0a57.png
Please describe the actual behaviour
I Cant select any Badges
Console errors:
http://puu.sh/spNMd/e6f5954129.png
HTML:
<img app:badge-src="AccountBadge.data" src="blob:chrome-extension%3A//cknihipnnkgolgdlfodbibfmdmhhbmlb/6f4505b8-895b-4d47-a265-8ba21b23f1b4">

What steps can be taken to reproduce the issue?
Not Sure but for me and my coworkers it doesnt work on private servers
Bug reproducible on Linux(64Bit)/Mac and Windows10(64Bit)
1. download newest screeps client
2. connect to private server for first time
3. select username
4. cant choose badge
