### ISSUE TITLE
lookForAtArea('terrain' not working in sim

### ISSUE THREAD

**Issue by Herbo4** [screeps/screeps#32]
Apologies if this is the wrong repo to post this in: I have utilized the lookForAtArea function to seemingly correctly populate a 3x3 grid looking for terrain types around sources. 
```
//find the active sources in the room
function findSources(r){
        var result= Array();
        r.find(FIND_SOURCES_ACTIVE).forEach(function(source) {
            result.push(source.pos);
        });
        //Peek at the result by uncommenting the line below
        //console.log("findSources: "+JSON.stringify(result))
        return result;
}

function countMiningSpots(r){
        var result = Array();
        //get the pos of each source
        var posList = findSources(r);
        //Peek at the result by uncommenting the line below
        console.log("posList: "+JSON.stringify(posList));
        var i = 0;
        posList.forEach(function(posObj){
            //Check out the posObj
            console.log("posObj: "+posObj)
            //search the 3x3 grid with the source at the center
            result= (r.lookForAtArea('terrain',(posObj.x)-1,(posObj.y)-1,(posObj.x)+1,(posObj.y)+1));
        })
        //Peek at the result by uncommenting the line below
        console.log("countMiningSpots: "+JSON.stringify(result));
}
```
The code above will produce an array that is a 3x3 representation of accurate x and y properties, but not accurate terrain types as indicated in the following image.
![screeps](https://cloud.githubusercontent.com/assets/12784083/20565272/e406e5dc-b15e-11e6-82f9-04081471094c.png)
I think this may be a flaw specific to the sim, but wanted to bring it to your attention regardless.

**Comment by artch** [comment]
This line is wrong:
```
result= (r.lookForAtArea('terrain',(posObj.x)-1,(posObj.y)-1,(posObj.x)+1,(posObj.y)+1));
```
Should be:
```
result= (r.lookForAtArea('terrain',(posObj.y)-1,(posObj.x)-1,(posObj.y)+1,(posObj.x)+1));
```

The method is `lookForAtArea(top, left, bottom, right)` (see [docs](http://support.screeps.com/hc/en-us/articles/203079011-Room#lookAtArea)).

**Comment by Herbo4** [comment]
Your method doesn't include a find constant.
