### ISSUE TITLE
describeExits() returns null for rooms created via CLI

### ISSUE THREAD

**Issue by mattregul** [screeps/screeps#35]
Using `describeExits(roomName)` on any rooms generated via the `CLI` will always return `null`, but works as expected on original rooms.

===================

**Example:**
in CLI:
`map.generateRoom("E1N1", {sources: 4, terrainType: 2});`
`map.generateRoom("E2N1", {sources: 4, terrainType: 2});`
`map.generateRoom("E3N1", {sources: 4, terrainType: 2});`

in-game:
`var exits = Game.map.describeExits('E2N1');`
`console.log(exits)` returns `null`

===================

**Links:**
Screeps CLI
- https://github.com/screeps/screeps#command-line-interface-cli

API describeExits
- http://support.screeps.com/hc/en-us/articles/203079191-Map#describeExits

Changelog - Build 27 - Addition of map.generateRoom
- http://support.screeps.com/hc/en-us/community/posts/209435465-PS-Changelog-build-27

**Comment by WhiteHalmos** [comment]
Should be fixed by https://github.com/screeps/driver/pull/5.

**Comment by artch** [comment]
Accepted solution in screeps/driver#5.
