### ISSUE TITLE
cpu load

### ISSUE THREAD

**Issue by keachi** [screeps/screeps#36]
Hi,
I run a server for multiple days, and the longer I run the server, the more rise the cpu usage and load (up to 100% of one core I think).
And because it used that much cpu, I deleted the bots on the server and restarted it, and the load is rising again, but not that fast as with the bots.
My setup:
Node 7.2.0
Python 2.7.12
2 User on the server
2 Cores of a Xeon E3-1220
8 GB RAM

**Comment by nreusch** [comment]
Same here. Tickrate gets really slow and that on a 3 cpu server with only 1 player with 1 room playing :/

**Comment by knaar13** [comment]
As said elsewhere, the issue appears to be node 7. Downgrade to node 6 (which is the stable long term support version) and the issue disappears. At least, I have been running all day with consistent CPU load anyway (which is a first, before with node 7 CPU reaches 100% within an hour or two).

When you downgrade node, make sure to rebuild npm packages with `npm rebuild` or the server will crash. You might need `npm rebuild -g` if you installed screeps globally.

**Comment by 2-B** [comment]
I can confirm that.
But the issue still exists and the [package.json line 25](https://github.com/screeps/screeps/blob/master/package.json#L25) should also be changed:
NodeJS >= 6.5.0 but < 7 (don't know the exact string).
