### ISSUE TITLE
Dependencies in READ.ME incorrect

### ISSUE THREAD

**Issue by soshimozi** [screeps/screeps#37]
You should probably note that node-gyp is a required dependency.  Not everyone is running on a fully installed distro or a Mac, so we may not have node-gyp installed.  Also, please note that any time using -g switch you should use sudo or run the account as root.  Otherwise you run the risk of the dreaded EACCESS error.

**Comment by artch** [comment]
You don't need to install node-gyp manually as a dependency, npm should install it automatically. Also, sudo is not required when you install Node.js using [nvm](https://github.com/creationix/nvm) (it's a recommended way to install it).

**Comment by soshimozi** [comment]
I wrote this awhile back when I was running on Raspbian Wheezy which this is not supported out of the box.  Another member kindly pointed me to Jessie and was rewarded with a simple install with no headaches.  I now have my Screeps server running on a Raspberry Pi 3 :D.  Thanks!
