### ISSUE TITLE
Support for ARM?

### ISSUE THREAD

**Issue by soshimozi** [screeps/screeps#38]
I noticed that there is no support for ARM targets.  I want to run Screeps on my Rasberry PI, but was unable to complete the build as it failed during the command  node-gyp rebuild -C native which makes me think it's a problem with the target processor - ARM in the case of Raspberry Pi.

**Comment by ags131** [comment]
Works fine on arm, though you may need to `apt-get install build-essentials` (Installs make, gcc, etc)

**Comment by soshimozi** [comment]
I have latest installed.  This is my development rpi.  It's a Pi 2 running Debian Wheezy.  I've updated to latest libraries and still no joy in build.  I was also unable to build on a Windows machine, but that's pretty much par for the course.  I'm going to spin up a VM running another distro to see if that helps.  Not ideal, because I wanted it to run on the pi, but at least I'll have a server running.

**Comment by ags131** [comment]
May need Debian Jessie, I don't know if the natives will build against the older Wheezy stuff.

**Comment by soshimozi** [comment]
Roger that.  I'll get Jessie installed.
