### ISSUE TITLE
Processes die constantly

### ISSUE THREAD

**Issue by tmapes** [screeps/screeps#39]
Ubuntu 16.04 LTS
Python 2.7
Nodejs 7
build-essentials installed
No matter what settings I change, this is all I get when attempting to run a server.

Server version 2.2.0
Starting all processes. Ports: 21025 (game), 21026 (cli)
[storage] process 2760 started
[backend] process 2770 started
[engine_main] process 2771 started
[engine_runner1] process 2777 started
[engine_processor1] process 2783 started
[engine_main] process 2771 exited with code 1, restarting...
[engine_runner1] process 2777 exited with code 1, restarting...
[engine_processor1] process 2783 exited with code 1, restarting...
[engine_main] process 2798 started
[engine_runner1] process 2804 started
[engine_processor1] process 2805 started
[engine_main] process 2798 exited with code 1, restarting...
[engine_runner1] process 2804 exited with code 1, restarting...
[engine_processor1] process 2805 exited with code 1, restarting...
^C

**Comment by tmapes** [comment]
After a few reinstalls, I was able to get it working correctly by installing all Pre-Reqs, rebooting, installing screeps without the -g parameter on npm, and then installing it with the -g param.

**Comment by mnpenner** [comment]
What worked for me was

```sh
mkdir screeps
cd screeps
npm i screeps
node_modules/.bin/screeps init
# paste Steam API key
node_modules/.bin/screeps start
```

Couldn't get the global install to work.
