### ISSUE TITLE
Launcher lag.

### ISSUE THREAD

**Issue by DeathTech154** [screeps/screeps#44]
Hi guys,

I have recently noticed that the launcher gets very slow and choppy after say a day or three.
Not all components but mainly the engine_main & later backend.

The lag seems to be generated by the fact that the system stores all notifications of the chronjob executions / tick progression / errors.
Although these are essential in some way to keep track of. We should be able to purge the data when it overflows to such an extent that we can't scroll through the component.

I would suggest either a command to purge the notifications / history or a "history limit" that can be set by the server admin to limit to x amount of messages.

For the moment I have had to no choice but to slow this down manually by removing the line. 
"console.log('Game time set to', gameTime);" from engine/dist/main.js to end that slowdown albeit temporarily.

**Comment by artch** [comment]
Is this about the GUI launcher or npm launcher?

**Comment by DeathTech154** [comment]
The server launcher shipped with the game.

**Comment by o4kapuk** [comment]
Should be [fixed](https://github.com/screeps/common/commit/fd9c332f824f4e7e72c38bf4184315b11e311112) in 3.4.0
