### ISSUE TITLE
BUG: automatic placed border walls - in claimable room

### ISSUE THREAD

**Issue by Wompi** [screeps/screeps#49]
Hey mates.

~~It seems that game automatic constructed walls are missing the 'ticksToLive' property~~

the API says: 
> ticksToLive	number	The amount of game ticks when the wall will disappear (only for automatically placed border walls at the start of the game).  

~~This makes it a bit hard to interact with this kind of walls. The Decay time is shown in the client GUI though.~~

After a little slack chat it seams the bug is not the TTL property. Rather there should none of these walls in a claimable room - see W86S33 - this room is claimable and has those wall in it 

Hope this helps
casegard

**Comment by o4kapuk** [comment]
Border walls on edges of a claimed room is a valid case.
