### ISSUE TITLE
How to get to the Web GUI?

### ISSUE THREAD

**Issue by mnpenner** [screeps/screeps#5]
Sorry, I'm probably misunderstanding something, but how do I get into the game after launching the server?

I've followed to "Console launcher" instructions and I can see that the server is running on port 21025 now. However, when I go to http://localhost:21025/ all I see is `Cannot GET /`. What am I missing?

**Comment by artch** [comment]
You have to use your Steam game client to connect to the server.

**Comment by scaytrase** [comment]
So there are no other options other than buy the game to access own private server?

**Comment by artch** [comment]
Yes, this is how Screeps works currently, but we expect some unofficial alternative clients to appear in the future.

**Comment by scaytrase** [comment]
Is there any place to subscribe?

**Comment by jakeNiemiec** [comment]
>we expect some unofficial alternative clients to appear in the future

Is that a blessing?

**Comment by TheRealMaxion** [comment]
@jakeNiemiec yes we are free to make our own clients as long as we don't steal code from the official client for it (since that is not open source).

**Comment by reneroth** [comment]
It'd be nice to see that part open source too, since the Steam client blows up my workstation, while in-browser works okay-ish.
