### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by Helios-vmg** [screeps/screeps#50]
I'd be helpful if the README gave at least a ballpark estimate for the hardware requirements, so the user can size up the hardware. Particularly the memory requirements.

**Comment by ags131** [comment]
With screeps is very hard to list hardware requirements at all, it will run on something as small/weak as a raspberry pi, and as strong has top end i7s and xeons. In the end, it depends on how many players and rooms you want to be able to run. I was hitting the bottleneck of the storage module being single-threaded long before ever hitting physical resource limits.

**Comment by Helios-vmg** [comment]
Not even something simple, like a server with less than 10 players, which is what most private servers are likely to run? Or at the very least some way to vaguely estimate the memory required. Like, will it run on 1 or 16 GB?

**Comment by ags131** [comment]
Not easily, although I will say from experience, its not very memory heavy, more CPU heavy than anything, and at that, only until the storage module hits 100% usage, at which point it bogs no matter what.

**Comment by mloftis** [comment]
Yeah the default storage rewrites the entire db.json which is...to say the least, suboptimal.  If you're trying to scale at all you'll have to use the mongo variant or write your own against something else.
