### ISSUE TITLE
BUG - spawn.renewCreep() broken in Simulation

### ISSUE THREAD

**Issue by travislaynewilson** [screeps/screeps#54]
Whenever I try to renew a creep in Simulation, all of my creeps freeze in place and the creep is not renewed. Here are the symptoms:

1. The creep is positioned correctly, near the spawn.
2. The spawn is not active.
3. Both creep.moveTo(...) and spawn.renewCreep(...) return a 0 response.
4. The creep does not renew.
5. All creeps in the room freeze up and do not process their actions while this is taking place.
6. All creeps can say things during this freeze-up, even if their actions are processed after the renewing creep's actions.
7. If I wait long enough, the creeps die.
8. If I stop the renewal in subsequent ticks, or if I suicide the renewing creep, everything returns to normal in subsequent ticks.
9. The freeze only occurs when the renewal starts; moving to spawn does not cause any adverse effects.
10. These things do not occur in World mode.
11. Others in Slack have confirmed this behavior.
12. This code is 4 months old, and has not been touched until today.

I rely heavily on Simulation for development, and this bug is preventing me from programming my strategy any further. Any thoughts?

**Comment by devmelon** [comment]
Same issue here, in the simulation room. spawn.renewCreep(creep) sometimes throws me a -7 ERR_INVALID_TARGET or an 0 OK. Usually an OK. Between script loads, where I only changed the output formatting of a console.log, the result shifted from a -7 to a 0.

**Comment by RogChav** [comment]
I'm having the same problem now. I move my creep right next to my spawn structure and I run the renew method, which returns 0 ('OK"). I don't like to add code to my real code base until I've tested it in simulation because it's easier to get feedback without any ramifications. Especially if I want to add more than one change, otherwise It'll be more of a hassle to debug if something does go wrong.

**Comment by TheRealMaxion** [comment]
I would recommend using private server for testing as there are a few things that don't work in simulation, I guess this would be one of them.

**Comment by artch** [comment]
Fixed now, thanks for reporting.
