### ISSUE TITLE
Enhancment: run Full tests

### ISSUE THREAD

**Issue by thigg** [screeps/screeps#56]
It would be nice to be able to create a test suite with a defined initial World setup (exported Gamestate) where one could run the simulation for a few ticks and check the result.

Szenario: Creep shows buggy behaviour. Export Gamestate. Add a test which use the Gamestate to fail the test. Fix bug. Test verifies its working.

**Comment by o4kapuk** [comment]
Sounds like a good idea for an excellent community project, but definitely not like a game issue, closing.
