### ISSUE TITLE
Github -> Game = No emoji's

### ISSUE THREAD

**Issue by shibdib** [screeps/screeps#57]
Minor issue, but going from webstorm -> github emoji's work fine. But from github -> game they don't encode correctly.

**Comment by monstic** [comment]
My emojis shows ok in visual code editor and in github, but in game or browser game don't work.

**Comment by starwar15432** [comment]
I also have had this issue.

**Comment by monstic** [comment]
hello? some answer about? :)

**Comment by ags131** [comment]
Works fine for me

**Comment by monstic** [comment]
do you use some editor with github? or do you edit here in github?

**Comment by ags131** [comment]
I edit in sublime_text3, push to github, and push from gulp

**Comment by monstic** [comment]
I'm using Visual Studio Code to edit and send to github,  but screeps auto syncronize with my github...

**Comment by nukeop** [comment]
I'm also experiencing this issue.

**Comment by KageJittai** [comment]
This depends wildly on the fonts available on your machine and having an updated browser.

You can see which emojis your browser font supports [here](http://unicode.org/emoji/charts/full-emoji-list.html).

[Here](https://github.com/eosrei/emojione-color-font) is a font installer for all major operating systems that provides emojis.

**Comment by nukeop** [comment]
This is untrue, since we're sending Unicode data to Github, then Screeps reads the same data from Github. The issue has nothing to do with installed fonts, browsers, or whatever, it's a problem with the code pulling function on the side of the Screeps server.

**Comment by logictests** [comment]
Anyone find a solution for this? it's happening for me too.  Using Atom on Windows.

**Comment by krunkster** [comment]
This is still a problem, and it's annoying.   At this point I have to drop github integration or switch to a bunch of String.codePointAt() calls or "\u{1F47E}" notation which is annoying.

**Comment by logictests** [comment]
I ended up just creating an 'emojis.js' and using variables instead of having to look up / memorize all the \u notations.

**Comment by o4kapuk** [comment]
The fix is already at PTR, we're going to deploy it to the production server together with Factories.

**Comment by o4kapuk** [comment]
It should be fixed now.
