### ISSUE TITLE
Cannot start screeps server

### ISSUE THREAD

**Issue by rem2016** [screeps/screeps#58]
I used command line to start server. However, it keep exiting and restarting. I use python2 and the settings about runner_cnt and processors_cnt are correct and the version of my node.js is 6.11.0.

ubuntu@xxx:~/screeps$ screeps start
Server version 2.7.1
Starting all processes. Ports: 21025 (game), 21026 (cli)
[storage] process 2028 started
[backend] process 2038 started
[engine_main] process 2039 started
[engine_runner1] process 2045 started
[engine_processor1] process 2051 started
[engine_runner1] process 2045 exited with code 1, restarting...
[engine_main] process 2039 exited with code 1, restarting...
[engine_processor1] process 2051 exited with code 1, restarting...
[backend] process 2038 exited with code 1, restarting...
[engine_runner1] process 2066 started
[engine_main] process 2067 started
[engine_processor1] process 2078 started
[backend] process 2084 started
[engine_runner1] process 2066 exited with code 1, restarting...
[engine_main] process 2067 exited with code 1, restarting...
[engine_processor1] process 2078 exited with code 1, restarting...
[backend] process 2084 exited with code 1, restarting...
[engine_runner1] process 2094 started
[engine_main] process 2095 started
[engine_processor1] process 2106 started
[backend] process 2112 started
[engine_runner1] process 2094 exited with code 1, restarting...
[engine_main] process 2095 exited with code 1, restarting...
[engine_processor1] process 2106 exited with code 1, restarting...
[backend] process 2112 exited with code 1, restarting...
[engine_runner1] process 2122 started
[engine_main] process 2123 started
[engine_processor1] process 2129 started
[backend] process 2140 started
[engine_runner1] process 2122 exited with code 1, restarting...
[engine_main] process 2123 exited with code 1, restarting...
[engine_processor1] process 2129 exited with code 1, restarting...
[backend] process 2140 exited with code 1, restarting...
[engine_runner1] process 2150 started
[engine_main] process 2156 started
[engine_processor1] process 2162 started
[backend] process 2168 started
[engine_runner1] process 2150 exited with code 1, restarting...
[engine_main] process 2156 exited with code 1, restarting...
[engine_processor1] process 2162 exited with code 1, restarting...
[backend] process 2168 exited with code 1, restarting...
[engine_runner1] process 2178 started
[engine_main] process 2184 started
[engine_processor1] process 2190 started
[backend] process 2196 started
[engine_runner1] process 2178 exited with code 1, restarting...
[engine_main] process 2184 exited with code 1, restarting...
[engine_processor1] process 2190 exited with code 1, restarting...
[backend] process 2196 exited with code 1, restarting...
[engine_runner1] process 2206 started
[engine_main] process 2212 started
[engine_processor1] process 2218 started
[backend] process 2224 started
[engine_runner1] process 2206 exited with code 1, restarting...
[engine_main] process 2212 exited with code 1, restarting...
[engine_processor1] process 2218 exited with code 1, restarting...
[backend] process 2224 exited with code 1, restarting...
[engine_runner1] process 2234 started
[engine_main] process 2235 started
[engine_processor1] process 2246 started
[backend] process 2252 started
[engine_runner1] process 2234 exited with code 1, restarting...
[engine_main] process 2235 exited with code 1, restarting...
[engine_processor1] process 2246 exited with code 1, restarting...
[backend] process 2252 exited with code 1, restarting...

**Comment by artch** [comment]
You might want to check per-process logs in the corresponding folder to check what's wrong with them.

**Comment by rem2016** [comment]
@artch The engine_main.log, engine_processor.log, engine_runner.log show as following. How can I solve it?

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:1018:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by ags131** [comment]
It looks like you installed the screeps package while node 4 was installed, try doing `npm uninstall -g screeps` and `npm install -g screeps` and try again

**Comment by rem2016** [comment]
Thanks, now I know where the problem is. But it didn't solve the problem...

I updated the npm, tried reinstalling screeps and init again in new directory then run `screeps start`, then I met the problem again with the same log information.

**Comment by Chrusciki** [comment]
I have the same issues, attempting to start a server on a raspberry pi, 
nodejs -v: 8.1.2
Python 2.7.9

**Comment by lytedev** [comment]
Have you all tried cloning the repository, running `npm install` and THEN running `node bin/screeps init && node bin/screeps.js start`?

It seems to be some issue with `npm i -g screeps` not properly installing the module's dependencies?

**Comment by Chrusciki** [comment]
that did it, i was using '-g' 

everything is working perfectly now. thank you!

**Comment by rem2016** [comment]
I was using '-g' too~!

Thanks

**Comment by lytedev** [comment]
I think this issue should remain open.

https://github.com/screeps/screeps/blame/master/README.md#L19 says to install using `-g` but it doesn't seem to work. I think there's an actual issue here. You SHOULD be able to use `npm i -g screeps` to install the server, but it doesn't work.

**Comment by artch** [comment]
Error `Module version mismatch` is always related to incompatibility between Node.js version and installed native npm modules versions and has nothing to do with Screeps code. `npm i -g screeps` is working fine on latest node `8.1.3` and npm `5.0.3` if installed correctly, we've just confirmed that.

**Comment by Jan0707** [comment]
I can confirm this error happens on node `8.4.0` and npm `5.3.0`

**Comment by artch** [comment]
Again -- this is not related to Screeps, it's your environment. Make a clean Node.js install if you cannot rebuild it properly.

**Comment by Jan0707** [comment]
Honestly I just installed node the other day, this is a new machine and screeps was the first package I installed globally.

**Comment by artch** [comment]
Just checked with node 8.4.0 and npm 5.3.0, it works fine.

Try to google this error. There is a lot of info on the Internet regarding it, it has absolutely nothing to do with Screeps.
