### ISSUE TITLE
Looks like it ignores the mods.json

### ISSUE THREAD

**Issue by sukapx** [screeps/screeps#59]
Hey there,

I've installed the Server as npm install -g screeps aswell as git clone && npm install.

Both versions do start and are playable, but it themes like it ignores the mods.json file totaly.

I checked the .screepssrc file
I've given it the parameter --modfile mods.json

also tried to give it the mods.example.json

so I tried to give some console output ... nothing
Tried to damage the mods.json file (adding a ; to break the JSON formatting) in hope to get any error ... nothing

Any ideas?

```
example-mods$ cat tick-duration.js
// Change tick duration to 200 ms

module.exports = function(config) {
;
    console.log('Increase tickrate!');
    if(config.engine) {
        config.engine.mainLoopMinDuration = 20;
    }
};
```
```
$ cat mods.json
{
;
  "mods": [
    "example-mods/tick-duration.js",
  ],
  "bots": {
    "simplebot": "node_modules/@screeps/simplebot/src"
  }
}

```

**Comment by kasami** [comment]
I solved this by changing the .screepssrc parameter to modsy.json (copying mods.json).

mods.json seems to be updated with some external values (workshop?) each time the server starts.

**Comment by Dragonisser** [comment]
Where the heck do i even need to put the damn mods.json. Neither does it work where it is from the start, nor renaming it or putting it at the first folder of the server.

**Comment by sukapx** [comment]
Well it's now running within a docker container:
`:~# cat start_docker_screeps.sh
#!/bin/bash
screen -AdmS screeps \
docker run \
    -it \
    --rm \
    --cpus="0.25" \
    -v ~/screeps:/screeps \
    -p 21025:21025 \
    --name screeps \
    node:6 \
    bash -c "cd /screeps;\
    npm i; \
    node_modules/.bin/screeps-launcher \
    --password creepy \
    --processors_cnt 1 \
    --runners_cnt 1 \
    start"`

Onething that's not nice is that the initializing of Modules is not shown in the main Log.
But it's written into the logfiles, and the Server does not exit with -1 if the modules did throw an error.

So it's pretty easy to think that they're not loaded at all.
