### ISSUE TITLE
Allow configuring game speed

### ISSUE THREAD

**Issue by bannmann** [screeps/screeps#6]
I want to use the local server for testing purposes. It would be great if there would be a configuration option or CLI command to set the game speed, similarly to the simulation mode.

**Comment by artch** [comment]
You can do this by adding a server mod, see [this example](https://github.com/screeps/launcher/blob/master/init_dist/mods/examples/tick-duration.js).

**Comment by ross-p** [comment]
Correct URL for the example is:

https://github.com/screeps/launcher/blob/master/init_dist/example-mods/tick-duration.js
