### ISSUE TITLE
Server won't start in Debian linux

### ISSUE THREAD

**Issue by mstahl** [screeps/screeps#61]
I'm getting this error, even after a full reinstall and reinit of my screeps directory:

```
Server version 2.8.2
Starting all processes. Ports: 21025 (game), 21026 (cli)
[storage] process 466 started
/screeps/node_modules/@screeps/launcher/lib/start.js:119
            throw new Error('Could not launch the storage process');
            ^

Error: Could not launch the storage process
    at Timeout.setTimeout [as _onTimeout] (/screeps/node_modules/@screeps/launcher/lib/start.js:119:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

The whole storage.log file is:

```
Loading mods from "/screeps/mods.json"
```

This is after a fresh `screeps init` on Debian linux running on ARM architecture.

**Comment by mstahl** [comment]
Ok, so, after much more investigation, I have a workaround but it's not great: installing Node 8.2.1 from source. I managed to get the screeps server running from a fresh install of Node 8.2.1 and a global install of screeps, in a freshly `screeps init`ed directory, but if I stop the server with Ctrl-C, when I try to start it back up again I get the same error as I did above. After that, for some reason, even re-`screeps init`ing the directory doesn't fix the problem, and I have to reinstall Node and Screeps.

I assume this is only a problem on ARM, which may indicate it's a Node issue, but with what little information I have right now if I post an issue with Node they'll just kick me back here.

One question: is there a more graceful way to stop the Screeps server, such as sending a SIGQUIT? I'm a little scared to try since it might fry my Screeps world again.

**Comment by mstahl** [comment]
This is happening in Ubuntu 64bit x86 too. I can run the server just fine in Windows, but only through Steam, so I can't then connect to the server from a different computer with my same Steam ID. Is anyone looking into this?

**Comment by topjor** [comment]
same, still having this issue when i try and create a server, with latest node8 version

**Comment by o4kapuk** [comment]
Is this still an issue?

**Comment by LordRatte** [comment]
Confirmed -- still a problem on Ubuntu 64bit with the default versions that come with the Steam download.

**Comment by Ronin11** [comment]
+1

**Comment by JQE** [comment]
anyone have any suggestions for this? I was hoping to run a private server on my linux box, but it starts once then every other time it just resets the runner. Looks like it might be an issue with the storage.....

**Comment by o4kapuk** [comment]
Can anyone provide logfiles?

**Comment by JQE** [comment]
I managed to get mine working. Turns out it is the version of isolate-vm i think.

I did an install of isolated-vm BEFORE i installed screeps and then it worked 100%
