### ISSUE TITLE
Fast ticks slow down over time

### ISSUE THREAD

**Issue by sparr** [screeps/screeps#66]
I am using the tick-duration example mod, with the min tick duration reduced to 20ms, in an attempt to run the simulation as fast as possible. When I start the server, it's running at about 8 ticks per second. A few minutes later, it has decreased to 4, then later 2. If I restart the server, it goes back to 8 immediately, then slows down again. I've heard it suggested that there could be a bottleneck around lokijs and/or logging causing this.

**Comment by googoid** [comment]
Encountering exactly same behavior here!

Node.js v9.2.0
4 CPU, 4GB RAM, SSD VM, running on Proxmox Hypervisor
CentOS 7

It's pretty frustrating, we thought we will run a test server to quickly test our code before deploying to live environment, but after a while the tick duration increases so much that it is even slower than on official screeps server.

Another interesting fact is that on the server there are only 4 simple bots and 2 real players which don't have any crazy AI and at initial server launch CPU usage is extremely low, when the tick duration increases the CPU usage raises up to 50%+ and stays pretty much constantly there.

**Comment by tedivm** [comment]
Unfortunately the default storage engine (lokijs) doesn't handle real load very well and seriously slows down over time. However there is a [mongo and redis](https://github.com/ScreepsMods/screepsmod-mongo) mod that scales far better.

**Comment by xondk** [comment]
unfortunately doesn't seem directly related to storage engine, at least not currently with my server.
`  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
10088 xon        20   0 1013M 74084 23440 S 63.2  0.1 13h45:36 /usr/bin/node /usr/lib/node_modules/screeps/node_modules/@screeps/engine/dist/processor.js
10095 xon        20   0 1008M 88236 23324 S 31.3  0.1 13h46:49 /usr/bin/node /usr/lib/node_modules/screeps/node_modules/@screeps/engine/dist/processor.js
10140 xon        20   0 1109M 87388 23748 R 18.6  0.1 14h05:43 /usr/bin/node /usr/lib/node_modules/screeps/node_modules/@screeps/driver/lib/runtime/runtime.js
10141 xon        20   0 1108M 92020 23784 R 18.0  0.1 14h06:48 /usr/bin/node /usr/lib/node_modules/screeps/node_modules/@screeps/driver/lib/runtime/runtime.js
10073 xon        20   0  999M 51064 23408 S 17.3  0.1  2h09:36 /usr/bin/node /usr/lib/node_modules/screeps/node_modules/@screeps/engine/dist/main.js`

Dedicated server, running ubuntu 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Intel® Core™ i7-6700
64 GB DDR4 RAM
2 x 240 GB SSD

which should be more then enough to handle screeps, yet after a while cpu is maxed out and it seems related to node version, previously ran with latest node 6, after latest update indicating node 8.9.3, I upgraded to that version of node. Which shows these problems, I had this prior to latest update as well, and the solution was to run node 6, but i'd really prefer being able to run a newer version of node, previously it was the storage module that maxed out the cpu, but now its processor/runtime/main

The fact is, that there's only like 3 people on this server with nothing crazy in our scripts, and 4 default bots.
It could still be lokijs, but it seems at least not directly related and more related to something in the different node versions.

**Comment by ags131** [comment]
processor and runtime having high CPU is normal, runtime runs user code and
processors run intent processing. The slowness is likely a direct result of
the storage module, they each do a lot of queries in bursts. While the
storage module may have a low average CPU, those bursts of queries will
easily max the CPU on storage for short periods and cause queries to be
slower. Especially since the server uptime looks to be over 14 hours. For
any long running server I recommend using mongo and redis, they solve that
issue by supplying a full database layer that can handle the query volumes.
screepsmod-mongo adds that capability with no extra configuration needed
other than installing mongo and redis and importing the database.

**Comment by ckleban** [comment]
+1. also seeing this slowness and the a restart of the server solves the issue

**Comment by MasterJochen** [comment]
Here is my temp fix a batch file restarting our server every 30 min
`start screeps_server.exe

:loop
timeout /T 1800 /NOBREAK 
echo Restart
taskkill /im screeps_server.exe
timeout /T 10 /NOBREAK
start screeps_server.exe
goto loop`

put this in a .bat file .
i know its not realy a fix but less anoying as to restart the server allways by hand.

**Comment by sshado** [comment]
I am also seeing this problem. Currently running the server on a dedicated Windows 10 machine with 2 cores and plenty of RAM. Tried using screepsmod-mongo but it didn't solve the issue.

When I first start the server it runs fast as expected because there is only one player running a 10 CPU script connected to the server. Within about one hour it will have slowed down significantly and if I log in after 12-24 hours then almost nothing will be moving.

**Comment by TheZoc** [comment]
This also happens on Debian Buster, running v10.15.3, with a more modest setting, 1 CPU, 2gb ram
(values have been adjusted on .screepsrc)

**Comment by fritogotlayed** [comment]
I'm also seeing this when using the configuration proposed on https://docs.screeps.com/contributed/ps_ubuntu.html. I've included a little workaround I have running on the personal server I maintain. While this keeps the server tick's feel responsive users may notice a stutter when the service restarts. Very occasionally I've had players/users reporting that their client appears frozen but if they navigate off the current room and back everything seems back to normal. 

### Crappy Workaround

I ended up getting around this by setting up a cron job that restarts the service every hour. It's a minor inconvenience but it keeps things "zippy enough" for my group. If you're not familiar with CRON expressions https://crontab.guru/ may be able to help you come up with one that works for you.

* ssh into your server
* (optional, if needed) `sudo su`
* `crontab -e` to open your cron tab editor
    * Use `0 * * * * systemctl restart screeps-world`

**Comment by ags131** [comment]
As of 3.3.0, the launcher has a `restart_interval` option, which defaults to 3600 seconds (1 hour). It auto-restarts the runner and processors, which usually helps with some of the slowdowns. If not using screepsmod-mongo, a full restart would be needed to reload and reconnect to the storage module. For longer running servers I recommend using screepsmod-mongo, performance tends to be much more stable.

**Comment by fritogotlayed** [comment]
Huge thanks ags131. I tried setting the `restart_interval` in the `.screepsrc` file after configuring the server as described in the link above, with MongoDB and Redis. For whatever reason we still experience performance degradation on the 3.3.0 branch from commit `1c4337e`. 

One thing that is odd to me I just noticed is that running `show dbs` after starting the mongo cli; I only see the default three databases. I'm wondering if the tutorial / walkthough page is missing a few steps. I will have to research this after the weekend as I'll be AFK for the next few days traveling. I'll definitely circle back and note any mis-configurations I have. If I can figure out how I may even create a PR for the documentation :-).

Thanks again for the heads-up / pointer that made me re-question my configuration!

**Comment by ags131** [comment]
Yes, all screeps data is in the `screeps` database by default, within that is collections for `users` `rooms` `rooms.objects`, etc

**Comment by fritogotlayed** [comment]
I forgot to update this thread. After I got back I did manage to get the mongo/redis solution working. I'm not sure why my first attempt didn't get connected. I ended up having to rebuild the instance. I've got a few players and four bots running on the machine and everything has been super smooth. Thanks again @ags131

**Comment by o4kapuk** [comment]
The storage performance degradation issue has been reproduced successfully, and we're working on the fix
