### ISSUE TITLE
Add Achievements

### ISSUE THREAD

**Issue by wolffman122** [screeps/screeps#67]
Hi Guys 
   Was thinking about having screeps get an achievement system implemented.  Would open up to the community for ideas for certain achievements.  Then for first pass just have it show on the website under view profile.  Maybe later on implement statues to put in your actual room.  Pretty cool idea to build a trophy garden and defend it.

**Comment by artch** [comment]
Please use our [Feature Requests forum](https://screeps.com/forum/category/12/feature-requests) to start such discussions. This issue tracker is for actual issues with the standalone server.
