### ISSUE TITLE
Property of undefined

### ISSUE THREAD

**Issue by minat0thelim3t** [screeps/screeps#69]
Hey so I've been playing for a little while and the code works fine in the normal world, but when I go into a simulation I get this error
TypeError: Cannot read property 'find' of undefined
    at Object.module.exports.loop:39:34
    at __mainLoop:1:15536
    at eval:2:4
    at Object.r.runCode:2:143856
Here's the code that it's getting it from:
[main copy.txt](https://github.com/screeps/screeps/files/1412737/main.copy.txt)

yeah, I'd like to know what's causing the problem before this causes the main world script to error out.

**Comment by sparr** [comment]
`var towers = Game.rooms.W78N2.find(FIND_STRUCTURES, {filter: (s) => s.structureType == STRUCTURE_TOWER});`

In the sim, there is only one room. `Game.rooms.W78N2` is undefined there.

That's actually the only place in your code where `.find` is used; follow those breadcrumbs next time.

**Comment by sparr** [comment]
Also, this issue tracker is not the best place to get general support/help. I recommend http://chat.screeps.com/

**Comment by artch** [comment]
This issue tracker is only for bug reports regarding Screeps server software, please use proper support channels.
