### ISSUE TITLE
Server won't start on debian

### ISSUE THREAD

**Issue by zamp** [screeps/screeps#70]
> Server version 2.10.4
> Starting all processes. Ports: 21025 (game), 21026 (cli)
> [storage] process 12165 started
> [backend] process 12175 started
> [engine_main] process 12180 started
> [engine_runner1] process 12181 started
> [engine_runner2] process 12187 started
> [engine_processor1] process 12192 started
> [engine_processor2] process 12203 started
> [engine_main] process 12180 exited with code 1, restarting...
> [engine_runner1] process 12181 exited with code 1, restarting...
> [engine_runner2] process 12187 exited with code 1, restarting...
> [engine_processor1] process 12192 exited with code 1, restarting...
> [engine_processor2] process 12203 exited with code 1, restarting...
> [engine_main] process 12215 started
> [engine_runner1] process 12216 started
> [engine_runner2] process 12221 started
> [engine_processor1] process 12227 started
> [engine_processor2] process 12236 started
> [engine_runner2] process 12221 exited with code 1, restarting...
> [engine_main] process 12215 exited with code 1, restarting...
> [engine_processor1] process 12227 exited with code 1, restarting...
> [engine_processor2] process 12236 exited with code 1, restarting...
> [engine_runner1] process 12216 exited with code 1, restarting...

Runner main and processor all throw out this same error

> module.js:515
>     throw err;
>     ^
> 
> Error: Cannot find module '../native/build/Release/native'
>     at Function.Module._resolveFilename (module.js:513:15)
>     at Function.Module._load (module.js:463:25)
>     at Module.require (module.js:556:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/lib/node_modules/screeps/node_modules/@screeps/driver/lib/index.js:863:18)
>     at Module._compile (module.js:612:30)
>     at Object.Module._extensions..js (module.js:623:10)
>     at Module.load (module.js:531:32)
>     at tryModuleLoad (module.js:494:12)
>     at Function.Module._load (module.js:486:3)

When I installed it the first time I had to manually create the weak directory in /usr/lib/... /screeps/node_modules/weak
I also had to manually run node-gyp rebuild in that directory

**Comment by sparr** [comment]
https://github.com/screeps/driver/blob/master/package.json

should be running the node-gyp rebuild for you. Have you tried installing everything not-globally?

**Comment by zamp** [comment]
local works, thanks
