### ISSUE TITLE
Game won't start, running in steam on NixOs

### ISSUE THREAD

**Issue by canndrew** [screeps/screeps#73]
Hi, I just bought this game but when I go to start it I get:

```
Opted-in Controller Mask: 0
Game update: AppID 464350 "", ProcID 18522, IP 0.0.0.0:0
>>> Adding process 18522 for game ID 464350
GameAction [AppID 464350, ActionID 10] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/shum/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/shum/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/shum/.local/share/Steam/steamapps/common/Screeps/nw: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
GameAction [AppID 464350, ActionID 10] : LaunchApp changed task to Completed with ""
>>> Adding process 18523 for game ID 464350
Game removed: AppID 464350 "", ProcID 18522 
```

Any ideas? Using `LD_LIBRARY_PATH` to tell it where `libgtk-3.so.0` is doesn't help, presumably because steam creates its own environments for games where they have exactly the libraries they need and all the environment variables set correctly. Or at least I thought that's what steam did. So I'm out of ideas for how I can get this running.

**Comment by artch** [comment]
This is an open source server project, not a support channel for Steam client.

**Comment by canndrew** [comment]
Where's a good place to post this then? If the game won't start then there's a bug in something.

**Comment by PostCrafter** [comment]
@canndrew the [screeps forum](https://screeps.com/forum/) would be a good starting point.

**Comment by canndrew** [comment]
I guess. I just figured you might want a bug open somewhere so that the issue can be tracked. (I assume I'm not the only person this has happened to since all I did was install then click play).
