### ISSUE TITLE
Port Forwarding Issue

### ISSUE THREAD

**Issue by graytonio** [screeps/screeps#8]
I am attempting to setup a server on a centos 7 server and can't seem to get the connection to go through from a remote connection. I have forwarded port 21025 to the server but still have not gotten a successful connection.

**Comment by artch** [comment]
You need to set up your system network settings in order to make your port accessible. Since this issue is completely unrelated to the Screeps server, I'm closing this ticket. You can check your [Slack chat](http://chat.screeps.com) (#servers channel) for assistance from the community.
