### ISSUE TITLE
Build Errors During Install On Windows

### ISSUE THREAD

**Issue by Luminaii** [screeps/screeps#80]
Hello,

I'm trying to install the server on Windows.
Node.JS version: 8.11.1
Python Version: 2.7.15
The build tools are installed using
"npm install --global --production windows-build-tools"
It also didn't work with visual studio 2017.
It also didn't work with visual studio 2015 with the recommend settings on the GitHub page of node-gyp.

When running "npm install screens" I'm running into a build error during the installation of node-gyp.
`isolate.obj : error LNK2001: unresolved external symbol "protected: static double __cdecl v8::Platform::SystemClockTime
Millis(void)" (?SystemClockTimeMillis@Platform@v8@@KANXZ) [C:\Users\Administrator\node_modules\isolated-vm\build\isolat
ed_vm.vcxproj]
C:\Users\Administrator\node_modules\isolated-vm\build\Release\isolated_vm.node : fatal error LNK1120: 1 unresolved exte
rnals [C:\Users\Administrator\node_modules\isolated-vm\build\isolated_vm.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd C:\Users\Administrator\node_modules\isolated-vm
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\package.json'
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN Administrator No description
npm WARN Administrator No repository field.
npm WARN Administrator No README data
npm WARN Administrator No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@1.6.0 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isolated-vm@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-05-12T16_07_53_345Z-debug.log`
[2018-05-12T16_07_53_345Z-debug.log](https://github.com/screeps/screeps/files/1997759/2018-05-12T16_07_53_345Z-debug.log)

Is there a dependency I'm missing or maybe the wrong version of Visual Studio. I can't quite figure this one out. I also tried installing node-gyp separately but that didn't work either.

**Comment by AidanIsAJew** [comment]
This is a problem with isolated-vm. The npm package is out of date.

> Can you try building from the source on github please? I think that'll work
for you. I just need to publish a new npm package.

(https://github.com/laverdet/isolated-vm/issues/65)

**Comment by Luminaii** [comment]
I'll try that, I will update.

**Comment by artch** [comment]
@laverdet any thoughts?

**Comment by Luminaii** [comment]
Just checked what I was doing with the isolated_vm package and I might not have installed it correctly as it doesn't appear to pickup my manual build. Can you give me some pointers for how to use that build?

**Comment by laverdet** [comment]
@Luminaii could you please try now with isolated-vm 1.6.1 on npm

**Comment by Luminaii** [comment]
It’s working fine now, thanks for the update!

**Comment by TheCrazyT** [comment]
Can't build with version v11.2.0, isolated-vm allways tries to find "v8-inspector.h", but this one is not inside the header-archive.
Compare yourself:
https://nodejs.org/download/release/v8.9.4/node-v8.9.4-headers.tar.gz (old version has it inside ...)
https://nodejs.org/download/release/v11.2.0/node-v11.2.0-headers.tar.gz (new version does not have it inside ...)
I wonder if you really need to downgrade in order to build this project, anybody has a different idea?

**Comment by o4kapuk** [comment]
Currently, screeps supports only nodejs v8
