### ISSUE TITLE
No response to command in tutorial

### ISSUE THREAD

**Issue by eadsjr** [screeps/screeps#81]
When I started the tutorial I opened the in-game console tab as requested and typed 'Game'. There was no response like the tutorial said there should be. The tutorial continued and when I type or copy the provided line there is no response. Also, nothing happens in-game in response to the command. I am unable to proceed in the expected fashion.

macOS High Sierra 10.13.4
Chrome Version 66.0.3359.139 (Official Build) (64-bit)
In my Chrome console:

/a/#!/sim/tutorial/1:1 The SSL certificate used to load resources from https://screeps.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
Navigated to https://screeps.com/a/
(index):211 GET https://screeps.com/a/app2/styles.bundle.js 404 ()
xtracking-0.1.js:1 this
(index):211 GET https://screeps.com/a/app2/styles.bundle.js 404 ()
render-engine.js?bust=1526036678756":1 
    PixiJS 4.6.1 - ✰ WebGL ✰      http://www.pixijs.com/    ♥♥♥ 
/a/#!/sim/tutorial/1:1 [.Offscreen-For-WebGL-0x7fe80912fc00]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.
badge-svg:1 GET https://screeps.com/api/user/badge-svg?username=Player%201 404 ()

**Comment by artch** [comment]
This issue tracker is for open source server project. Please use the in-game "Report a problem" menu item to get help regarding general issues.
