### ISSUE TITLE
Construction sites don't get removed from the client-side

### ISSUE THREAD

**Issue by kkirkfield** [screeps/screeps#87]
Steps to reproduce:
1. Get to RCL 2
2. Place 5 extension construction sites
3. Go back to RCL 1
4. Build the construction sites
5. Get back to RCL 2
6. Click on the construction site and click destroy, or try to destroy the construction site via code
7. The game object with the id of the construction site no longer exists and you can't destroy it, but it still shows on the client
8. Restart the client
9. The construction sites now disappear

The client should remove the construction sites when they are finished being built, even if the RCL isn't high enough to support that structure. Either that, or don't allow building of construction sites for structures that can't be used at the current RCL.

**Comment by o4kapuk** [comment]
Should be fixed currrently.
