### ISSUE TITLE
Web frontend without steam installed?

### ISSUE THREAD

**Issue by bubthegreat** [screeps/screeps#88]
I've got a standalone server I set up at home, but I'd like to play from my work laptop, and can't install steam for the steam game engine - is there any plan to allow the standalone server to have a web portal access that doesn't require running steam?

**Comment by tedivm** [comment]
Join #client_dev on the slack network to hear about community efforts on this part.

**Comment by o4kapuk** [comment]
Currently, we don't have plans to publish our web client.
