### ISSUE TITLE
Screeps install stuck at CXX(target) Release/obj.target/isolated_vm/src/module_handle.o

### ISSUE THREAD

**Issue by RubenNijhuis** [screeps/screeps#89]
Hi, i tried installing screeps on my Raspberry Pi 3b+ but everytime i try it doesn't get past this: 
![screen shot 2018-09-22 at 12 21 49](https://user-images.githubusercontent.com/30152747/45916188-20226e80-be62-11e8-8d53-6a1b027a0697.png)

I installed it using
`npm install screeps`

I am on node version `v8.12.0`
NPM is on version `6.4.1`
Python is on `2.7`

### Excpected output
For the installation to finish

?? Is there something i am missing that i misread on the docs?

EDIT::
I installed/updated node-gyp maybe it will fix it, still trying

**Comment by stephanepiriou** [comment]
I had the same issue on a vps with only 2GB memory.

To create a swap file and activate it, do as follow as root (or sudo) user :
`dd if=/dev/zero of=/swapper bs=1M count=2048`
`mkswap /swapper`
`swapon /swapper`
 
To check if the swap file

Then, as screeps user, you can :
`npm install sceeps`

After completion of the install process
 you can delete your swap partition as root (or sudo) user :
`swapoff /swapper`
`rm /swapper`

**Comment by o4kapuk** [comment]
That sounds like an isolated-vm issue, are you able to install it alone? If it doesn't install either, please create the issue at [ivm module page](https://github.com/laverdet/isolated-vm).
