### ISSUE TITLE
lookFor(LOOK_TERRAIN) returns invalid value. (swamp instead of wall)

### ISSUE THREAD

**Issue by BarryOSeven** [screeps/screeps#90]
When I run this code:
`console.log(JSON.stringify(new RoomPosition(6,38,"E53N6").lookFor(LOOK_TERRAIN)));`

It returns a "swamp" which should be a "wall"

Here is a link to the room:
https://screeps.com/a/#!/room/shard2/E53N6

**Comment by BarryOSeven** [comment]
`console.log(JSON.stringify(Game.map.getTerrainAt(new RoomPosition(6,38,"E53N6"))))
`
[13:15:01] [shard2]Method `Game.map.getTerrainAt` is deprecated and will be removed. Please use a faster method `Game.map.getRoomTerrain` instead.
[13:15:01] [shard2]"wall"

**Comment by artch** [comment]
Fixed, thanks.

**Comment by artch** [comment]
Although, please don't use GitHub issue tracker for MMO bug reports, it's only for open-source server code base.

**Comment by BarryOSeven** [comment]
Alright, sorry about that. Thanks for fixing it!
