### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by japercaper** [screeps/screeps#91]
I get a boatload of issues when installing npm for the screeps server. I'm on Ubuntu 16 LTS. Here are the errors:

> isolated-vm@1.7.2 install /home/screeps/world/node_modules/isolated-vm
> node-gyp rebuild --release -j 4

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onread (net.js:622:25)
gyp ERR! System Linux 4.10.0-28-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /home/screeps/world/node_modules/isolated-vm
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/screeps/world/package.json'
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN world No description
npm WARN world No repository field.
npm WARN world No README data
npm WARN world No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@1.7.2 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isolated-vm@1.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sysadmin/.npm/_logs/2018-10-14T14_50_24_562Z-debug.log

**Comment by o4kapuk** [comment]
Did you install the necessary build/dev tools? (hint: sudo apt install -y build-essential tcl git for ubuntu)

**Comment by japercaper** [comment]
Yep. Did it again just in case I'm losing my mind:
======
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
tcl is already the newest version (8.6.0+9).
git is already the newest version (1:2.7.4-0ubuntu1.5).
======
