### ISSUE TITLE
Screeps without Steam?

### ISSUE THREAD

**Issue by japercaper** [screeps/screeps#92]
Hello,
I teach Info Tech at a high school. I/we have installed the standalone Screeps server on an Ubuntu server. But we cannot run Steam because the school blocks it. Is there a way around this? 

When we fire up the Steam client, it tries to update via the internet, which it cannot find, and it crashes. I've looked at several 'solutions' to prevent (or trick) Steam from trying to update, to no avail. 

Ideas or are we F-10-D-A (say it fast)?

Thanks,
TomT

**Comment by o4kapuk** [comment]
Currently, we have no plans on a DRM-free version of the Screeps client.
The only way to play without steam is the official public server via a web browser.
