### ISSUE TITLE
Main loop reset! Stage: waitForUsers

### ISSUE THREAD

**Issue by OfirYaron** [screeps/screeps#93]
Local server run for around half an hour, maybe a thousand ticks and suddenly get stuck,

`engine_main` gives the following:
```
Main loop reset! Stage: waitForUsers
Game time set to 56122
Main loop reset! Stage: waitForUsers
Game time set to 56123
...
```

`backend` gives the following:
```
Unhandled rejection: error: Can't set headers after they are sent
at validateHeader (_header_outgoing.js:494:11)
```

If I reset the server everything goes back to normal, for half an hour and it happens again

server version: 3.1.7

**Comment by edhaase** [comment]
Can confirm. Seems limited to steam private server, duration of run before halt is random.

Times out in stage waitForUsers, unsure if processors fall over or simply take too long to complete. User code stops executing but decay timers continue ticking.

**Comment by OfirYaron** [comment]
found others complaining on the same issue:
https://screeps.com/forum/topic/2242/main-loop-reset-stage-waitforusers

**Comment by OfirYaron** [comment]
11.1.0

**Comment by o4kapuk** [comment]
As far as I can see, isolated-vm currently does not support node 11 (see https://github.com/laverdet/isolated-vm)
I'd recommend LTS versions (10. or even 8.11 which is best tested to date)

**Comment by edhaase** [comment]
I'm using whatever is bundled with the steam private server

**Comment by klugemonkey** [comment]
I'm using v8.11.2 and having this issue (specifically nodejs 8.11.2~dfsg-1 on Debian).  Might also be related to tick delays getting longer and longer.  Seems to get worse and worse eventually throwing these Main loop reset! Stage: waitForUsers every increment of Game time in the engine_main.log.  It is also showing a lot of isolated-vm timeouts on engine_runner.log, but then isn't v8.11.2 supposedly a working version?

[engine_main.log](https://github.com/screeps/screeps/files/2690386/engine_main.log)
[engine_runner.log](https://github.com/screeps/screeps/files/2690387/engine_runner.log)

**Comment by o4kapuk** [comment]
We were able to reproduce the issue and now working on the fix.

**Comment by o4kapuk** [comment]
Should be [fixed](https://github.com/screeps/common/commit/fd9c332f824f4e7e72c38bf4184315b11e311112) in 3.4.0

**Comment by Hiestaa** [comment]
If somebody is coming to this issue again, try re-installing Screeps. 

I was experiencing this issue from an old install from before this bug was fixed. The game was kept up-to-date by my screeps client, but I was still experiencing the problem.

Deleting all files in the steam game folder then doing a verification in the steam client solved the issue. I believe a fresh, clean install would have done the same.
