### ISSUE TITLE
Build Tools in ReadMe

### ISSUE THREAD

**Issue by sshado** [screeps/screeps#94]
In the ReadMe.md it specifies that microsoft build tools are needed. It may be helpful to specify that anyone installing this on a Windows machine can also get [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) if they don't want to install the full Visual Studio. You just need to launch VS Build Tools, modify its installation, and add C++ development to the list of packages. It still comes in at around 4.52 GB but it's easier to fit onto server disks.

Thanks so much for the great ReadMe!

**Comment by ags131** [comment]
You can also just `npm install -g windows-build-tools` and it will install them for you.
