### ISSUE TITLE
npm installation failed on ubuntu 16.04 aliyun ECS

### ISSUE THREAD

**Issue by Weaverzhu** [screeps/screeps#96]
### Message:
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.
npm ERR! Linux 4.4.0-142-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "screeps"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! isolated-vm@1.7.10 install: `node-gyp rebuild --release -j 4`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the isolated-vm@1.7.10 install script 'node-gyp rebuild --release -j 4'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the isolated-vm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild --release -j 4
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs isolated-vm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls isolated-vm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
### description
I tried
```
sudo apt install nodejs
sudo npm install node-gyp
sudo npm install screeps
```
and python27 & building-essentials seems are already on my server

**Comment by ags131** [comment]
You need node 8, the nodejs in the ubuntu repos is outdated
