### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by ffMathy** [screeps/screeps#98]
It would be awesome if there was an official docker image for the server, that included redis caching.

**Comment by RvstFyth** [comment]
Check this link for ags his docker image
https://github.com/ags131/docker-screeps-server

**Comment by ffMathy** [comment]
But that is not official - it is third party right?

And also, it does not seem to use Redis for caching?

**Comment by ags131** [comment]
Its not official and doesn't contain redis. And shouldn't contain redis IMO. The Docker way is to have one service per container, therefore you should actually have 3 containers, screeps, redis, and mongo. Using something like docker-compose makes it simple. Also, the stock server doesn't support redis, thats only available through my screepsmod-mongo mod.

**Comment by ffMathy** [comment]
I made my own `docker-compose.yml` file for it here: https://github.com/ffMathy/Screeps.Server.Docker

It is also on Docker Hub.
