### ISSUE TITLE
Server not generating controllers in rooms

### ISSUE THREAD

**Issue by ffMathy** [screeps/screeps#99]
![image](https://user-images.githubusercontent.com/2824010/56326147-2917bc00-6175-11e9-8efc-c43e584ed17c.png)
See attached screenshot. I can't spawn anywhere on my newly created private server. Is this a known problem that has a solution?

**Comment by o4kapuk** [comment]
This looks like a corrupt database. Please try system.resetAllData() in the server's CLI

**Comment by ffMathy** [comment]
This apparently needs to be done every time. `system.resetAllData()` works, but has to be done every time I set up the server from scratch.

**Comment by o4kapuk** [comment]
Could you please be more specific about server type (bundled with Steam Client, installed from npm, compiled from the sources, or got somehow else), the server version (and all components if possible), used mods, and node.js version?

**Comment by ffMathy** [comment]
Yes, that's quite simple.

This docker-compose file reproduces the error consistently every time:

https://github.com/ffMathy/Screeps.Server.Docker/blob/master/docker-compose.yml

**Comment by o4kapuk** [comment]
screepsmod_mongo is a community project, the issues about it should be created at [the mod page](https://github.com/ScreepsMods/screepsmod-mongo) instead.

**Comment by ffMathy** [comment]
But is this a bug happening there though?

**Comment by o4kapuk** [comment]
If there is a bug, it's doesn't belong to this project.
